version: "3"
services:
  blockchain:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    image: revpop-core-samples
    expose:
    - 8090

  # Cloud storage - IPFS
  cloud:
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=lowpower

  samples:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: revpop-samples
    links:
      - blockchain
      - cloud
    volumes:
      # Uncomment /app volume to sync project files with the container. Adjust the .env file to work in the container.
      # - ./:/app
      - /app/node_modules
      - /app/demo/node_modules
